# Generated by Django 5.2.5 on 2025-11-28 15:17

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_picture",
            field=common.fields.OptimizedImageField(
                blank=True, null=True, upload_to="team_pictures/"
            ),
        ),
    ]
