# Generated by Django 5.2.5 on 2025-11-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='tournaments.rank',
            ),
        ),
        migrations.AddField(
            model_name='ingameid',
            name='game',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='tournaments.game',
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ingameid',
            unique_together={('user', 'game')},
        ),
    ]
