# Generated by Django 5.2.4 on 2025-07-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_teaminvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_picture",
            field=models.ImageField(blank=True, null=True, upload_to="team_pictures/"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
