# Generated by Django 5.2.8 on 2026-01-01 09:25

import common.fields
import common.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_handle_duplicate_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=common.fields.OptimizedImageField(
                blank=True,
                null=True,
                upload_to=common.utils.files.get_sanitized_upload_path,
            ),
        ),
    ]
