# Generated by Django 5.2.4 on 2025-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
