# Generated by Django 5.2.4 on 2025-07-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_rank_tournament_max_rank_tournament_min_rank"),
        ("users", "0006_user_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tournaments.rank",
            ),
        ),
    ]
