# Generated by Django 5.2.4 on 2025-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_rank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AddField(
            model_name="team",
            name="max_members",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
