# Generated by Django 5.2.5 on 2025-08-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import shortuuid


def generate_referral_codes(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.referral_code = shortuuid.uuid()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options_team_max_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.RunPython(generate_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=22, unique=True),
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referred",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
