# Generated by Django 5.2.5 on 2025-11-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0022_alter_match_participant1_team_and_more"),
        ("users", "0010_user_is_phone_verified"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="TeamInvitation",
        ),
        migrations.DeleteModel(
            name="TeamMembership",
        ),
    ]
