# Generated by Django 5.2.5 on 2025-11-14 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_teaminvitation_team_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="is_active",
        ),
        migrations.AddField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="otp",
            name="identifier",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
