# Generated by Django 5.2.5 on 2025-11-28 15:17

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="id_card_image",
            field=common.fields.OptimizedImageField(
                blank=True, null=True, upload_to="verification_images/"
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="selfie_image",
            field=common.fields.OptimizedImageField(
                blank=True, null=True, upload_to="verification_images/"
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="video",
            field=common.fields.OptimizedVideoField(
                blank=True, null=True, upload_to="verification_videos/"
            ),
        ),
    ]
