# Generated by Django 5.2.8 on 2025-12-18 11:05

import common.fields
import common.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0002_alter_verification_id_card_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="verification",
            name="id_card_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                null=True,
                upload_to=common.utils.files.get_sanitized_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="selfie_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                null=True,
                upload_to=common.utils.files.get_sanitized_upload_path,
            ),
        ),
    ]
