FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl build-essential

# Set environment variables for the Rust mirror
ENV RUSTUP_DIST_SERVER=https://mirror.iranserver.com/rust
ENV RUSTUP_UPDATE_ROOT=https://mirror.iranserver.com/rust/rustup

# Install Rust from the mirror
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Now, install celery-exporter
RUN pip install celery-exporter

ENTRYPOINT ["celery-exporter"]
