# Generated by Django 5.2.4 on 2025-07-14 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="participant1_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant1",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="participant1_object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="participant2_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant2",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="participant2_object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="rules",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("team", "Team")],
                default="individual",
                max_length=20,
            ),
        ),
    ]
