from celery import shared_task
from django.utils import timezone
from blog.models import Post


@shared_task
def create_bot_article():
    """
    A Celery task to create a new blog post authored by the bot.
    This task is intended to be triggered when the bot is activated.
    """
    from .models import BotSettings

    try:
        bot_settings = BotSettings.objects.get(name="AtomGameBot")
        author = bot_settings.author

        if not author:
            # Optionally log this event for monitoring purposes
            return "AtomGameBot has no author assigned. Cannot create post."

        # Create a unique title for the article
        title = f"AtomGameBot Article - {timezone.now().strftime('%Y-%m-%d %H:%M:%S')}"
        content = "This is an automated article generated by AtomGameBot."

        Post.objects.create(
            title=title,
            author=author,
            content=content,
            status='published'
        )

        return f"Successfully created article: {title}"

    except BotSettings.DoesNotExist:
        # Optionally log this event
        return "BotSettings for AtomGameBot not found. Cannot create post."
