# Generated by Django 5.2.8 on 2025-12-12 15:20
import logging
from django.db import migrations
from django.db.utils import ProgrammingError

logger = logging.getLogger(__name__)

def create_pg_stat_statements_extension(apps, schema_editor):
    """
    Creates the pg_stat_statements extension if it doesn't exist.
    The operation is only attempted on PostgreSQL databases.
    """
    if schema_editor.connection.vendor != 'postgresql':
        logger.info("Skipping pg_stat_statements extension creation: not a PostgreSQL database.")
        return

    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_stat_statements;")
            logger.info("Successfully enabled pg_stat_statements extension.")
    except ProgrammingError:
        logger.warning(
            "Could not create pg_stat_statements extension. "
            "This is likely due to insufficient database privileges. "
            "Please create it manually as a superuser if you need this functionality."
        )

def reverse_func(apps, schema_editor):
    """
    Reverse function for the migration.
    """
    pass


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_pg_stat_statements_extension, reverse_func),
    ]
