# Generated by Django 5.2.5 on 2025-11-17 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("round", models.IntegerField()),
                (
                    "result_proof",
                    models.ImageField(
                        blank=True, null=True, upload_to="private_result_proofs/"
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_disputed", models.BooleanField(default=False)),
                ("dispute_reason", models.TextField(blank=True)),
                ("room_id", models.CharField(blank=True, max_length=100)),
                ("password", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("checked_in", "Checked-in"),
                            ("eliminated", "Eliminated"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "prize",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="ranks/")),
                ("required_score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="report_evidence/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("team_deathmatch", "Team Deathmatch"),
                            ("battle_royale", "Battle Royale"),
                        ],
                        default="team_deathmatch",
                        max_length=20,
                    ),
                ),
                ("max_participants", models.PositiveIntegerField(default=100)),
                (
                    "winner_slots",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum number of winners eligible for rewards. Set to 1 for champion-only payouts.",
                    ),
                ),
                ("team_size", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_free", models.BooleanField(default=True)),
                ("is_token_based", models.BooleanField(default=False)),
                (
                    "entry_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prize_pool",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total prize pool in Rial.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("rules", models.TextField(blank=True)),
                ("countdown_start_time", models.DateTimeField(blank=True, null=True)),
                ("required_verification_level", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("rgb_code", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="tournament_images/")),
            ],
        ),
        migrations.CreateModel(
            name="WinnerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="winner_submissions/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("hero_banner", "Hero Banner"),
                            ("cta_banner", "CTA Banner"),
                            ("game_image", "Game Image"),
                            ("thumbnail", "Thumbnail"),
                            ("icon", "Icon"),
                            ("slider", "Slider"),
                            ("illustration", "Illustration"),
                            ("promotional_banner", "Promotional Banner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="game_images/")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tournaments.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managers",
                        to="tournaments.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Manager",
                "verbose_name_plural": "Game Managers",
            },
        ),
        migrations.AddField(
            model_name="gamemanager",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="participant1_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_participant1",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="participant1_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_participant1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="participant2_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_participant2",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="participant2_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_participant2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_matches",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.match"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.game"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="max_rank_tournaments",
                to="tournaments.rank",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="min_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="min_rank_tournaments",
                to="tournaments.rank",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="tournaments",
                through="tournaments.Participant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="tournaments", to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="top_players",
            field=models.ManyToManyField(
                blank=True, related_name="top_placements", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="top_teams",
            field=models.ManyToManyField(
                blank=True, related_name="top_placements", to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="tournaments.tournamentcolor",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="tournaments.tournamentimage",
            ),
        ),
        migrations.AddField(
            model_name="winnersubmission",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="winnersubmission",
            name="winner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamemanager",
            unique_together={("user", "game")},
        ),
        migrations.AlterUniqueTogether(
            name="scoring",
            unique_together={("tournament", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("user", "tournament")},
        ),
    ]
