# Generated by Django 5.2.8 on 2025-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_alter_gameimage_image_alter_match_result_proof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("coming_soon", "Coming Soon"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("checked_in", "Checked-in"),
                    ("eliminated", "Eliminated"),
                ],
                db_index=True,
                default="registered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
