# Generated by Django 5.2.8 on 2025-12-01 15:34

import common.fields
import common.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_alter_gameimage_image_alter_match_result_proof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("coming_soon", "Coming Soon"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gameimage",
            name="image",
            field=common.fields.OptimizedImageField(
                upload_to=common.utils.files.get_sanitized_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="result_proof",
            field=common.fields.OptimizedImageField(
                blank=True,
                null=True,
                upload_to=common.utils.files.get_sanitized_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("checked_in", "Checked-in"),
                    ("eliminated", "Eliminated"),
                ],
                db_index=True,
                default="registered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="image",
            field=common.fields.OptimizedImageField(
                upload_to=common.utils.files.get_sanitized_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="evidence",
            field=common.fields.OptimizedImageField(
                blank=True,
                null=True,
                upload_to=common.utils.files.get_sanitized_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="tournamentimage",
            name="image",
            field=common.fields.OptimizedImageField(
                upload_to=common.utils.files.get_sanitized_upload_path
            ),
        ),
    ]
