# Generated by Django 5.2.4 on 2025-07-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_winnersubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('hero_banner', 'Hero Banner'), ('cta_banner', 'CTA Banner'), ('game_image', 'Game Image'), ('thumbnail', 'Thumbnail'), ('icon', 'Icon'), ('slider', 'Slider'), ('illustration', 'Illustration'), ('promotional_banner', 'Promotional Banner')], max_length=20)),
                ('image', models.ImageField(upload_to='game_images/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tournaments.game')),
            ],
        ),
    ]
