# Generated by Django 5.2.4 on 2025-07-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0007_tournament_countdown_start_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="ranks/")),
                ("required_score", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="max_rank_tournaments",
                to="tournaments.rank",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="min_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="min_rank_tournaments",
                to="tournaments.rank",
            ),
        ),
    ]
