# Generated by Django 5.2.8 on 2025-12-12 11:40

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0007_report_tournament_optional_match"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winnersubmission",
            name="video",
        ),
        migrations.AddField(
            model_name="winnersubmission",
            name="image",
            field=common.fields.OptimizedImageField(
                blank=True, null=True, upload_to="winner_submissions/"
            ),
        ),
    ]
