# Generated by Django 5.2.8 on 2025-12-12 15:22
import logging
from django.db import migrations

logger = logging.getLogger(__name__)

def create_concurrent_index(apps, schema_editor):
    """
    Creates an index concurrently, only on PostgreSQL databases.
    """
    if schema_editor.connection.vendor != 'postgresql':
        logger.info("Skipping concurrent index creation: not a PostgreSQL database.")
        return

    with schema_editor.connection.cursor() as cursor:
        # Using IF NOT EXISTS to make it safe to re-run.
        cursor.execute("""
            CREATE INDEX CONCURRENTLY IF NOT EXISTS tournaments_match_tourn_id_status_idx
            ON tournaments_match (tournament_id, status);
        """)

def drop_concurrent_index(apps, schema_editor):
    """
    Drops the index concurrently, only on PostgreSQL databases.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP INDEX CONCURRENTLY IF EXISTS tournaments_match_tourn_id_status_idx;")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("tournaments", "0008_remove_winnersubmission_video_winnersubmission_image"),
    ]

    operations = [
        migrations.RunPython(create_concurrent_index, drop_concurrent_index),
    ]
