# Generated by Django 5.2.4 on 2025-07-27 10:24

from django.db import migrations


def create_ranks(apps, schema_editor):
    Rank = apps.get_model("tournaments", "Rank")
    ranks = [
        {"name": "Bronze 1", "required_score": 0},
        {"name": "Bronze 2", "required_score": 100},
        {"name": "Bronze 3", "required_score": 200},
        {"name": "Silver 1", "required_score": 300},
        {"name": "Silver 2", "required_score": 400},
        {"name": "Silver 3", "required_score": 500},
        {"name": "Gold 1", "required_score": 600},
        {"name": "Gold 2", "required_score": 700},
        {"name": "Gold 3", "required_score": 800},
        {"name": "Diamond 1", "required_score": 900},
        {"name": "Diamond 2", "required_score": 1000},
        {"name": "Diamond 3", "required_score": 1100},
    ]
    for rank in ranks:
        Rank.objects.create(**rank)


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_rank_tournament_max_rank_tournament_min_rank"),
    ]

    operations = [
        migrations.RunPython(create_ranks),
    ]
