# Generated by Django 5.2.4 on 2025-07-27 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0009_auto_20250727_1024"),
        ("users", "0007_user_rank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="top_players",
            field=models.ManyToManyField(
                blank=True, related_name="top_placements", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="top_teams",
            field=models.ManyToManyField(
                blank=True, related_name="top_placements", to="users.team"
            ),
        ),
    ]
