# Generated by Django 5.2.8 on 2025-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0009_add_tournament_status_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
