# Generated by Django 5.0.4 on 2024-05-18 10:20

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Game = apps.get_model('tournaments', 'Game')
    Tournament = apps.get_model('tournaments', 'Tournament')

    for instance in Game.objects.all():
        if not instance.slug:
            slug = slugify(instance.name, allow_unicode=True)
            if not slug:
                slug = "game"

            counter = 1
            original_slug = slug
            while Game.objects.filter(slug=slug).exists():
                slug = f'{original_slug}-{counter}'
                counter += 1
            instance.slug = slug
            instance.save(update_fields=['slug'])

    for instance in Tournament.objects.all():
        if not instance.slug:
            slug = slugify(instance.name, allow_unicode=True)
            if not slug:
                slug = "tournament"

            counter = 1
            original_slug = slug
            while Tournament.objects.filter(slug=slug).exists():
                slug = f'{original_slug}-{counter}'
                counter += 1
            instance.slug = slug
            instance.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_game_slug_tournament_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
