# Generated by Django 5.2.8 on 2025-12-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0009_add_tournament_status_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winnersubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
