# Generated by Django 5.2.4 on 2025-07-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0010_tournament_top_players_tournament_top_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="prize",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
