# Generated by Django 5.2.8 on 2025-12-13 18:02

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Game = apps.get_model("tournaments", "Game")
    Tournament = apps.get_model("tournaments", "Tournament")

    for instance in Game.objects.iterator():
        if not instance.slug:
            slug = slugify(instance.name, allow_unicode=True)
            original_slug = slug
            counter = 1
            while Game.objects.filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1
            instance.slug = slug
            instance.save(update_fields=['slug'])

    for instance in Tournament.objects.iterator():
        if not instance.slug:
            slug = slugify(instance.name, allow_unicode=True)
            original_slug = slug
            counter = 1
            while Tournament.objects.filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1
            instance.slug = slug
            instance.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0010_game_slug_tournament_slug"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
