# Generated by Django 5.2.8 on 2025-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0011_populate_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
