# Generated by Django 5.2.8 on 2025-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0011_alter_slug_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="registration_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="registration_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
