# Generated by Django 5.2.4 on 2025-08-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0012_gamemanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="dispute_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="match",
            name="password",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="match",
            name="room_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
