# Generated by Django 5.2.8 on 2025-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0012_tournament_registration_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
