# Generated by Django 5.2.4 on 2025-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0013_match_dispute_reason_match_password_match_room_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="max_participants",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="tournament",
            name="mode",
            field=models.CharField(
                choices=[
                    ("team_deathmatch", "Team Deathmatch"),
                    ("battle_royale", "Battle Royale"),
                ],
                default="team_deathmatch",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="team_size",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
