# Generated by Django 5.2.5 on 2025-08-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0014_tournament_max_participants_tournament_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="tournament_images/")),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="tournaments.tournamentimage",
            ),
        ),
    ]
