# Generated by Django 5.2.5 on 2025-08-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0014_tournament_max_participants_tournament_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="tournament_images/"
            ),
        ),
    ]
