# Generated by Django 5.2.5 on 2025-08-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0015_tournamentimage_tournament_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("rgb_code", models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="tournaments.tournamentcolor",
            ),
        ),
    ]
