# Generated by Django 5.2.5 on 2025-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0016_tournamentcolor_tournament_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
