# Generated by Django 5.2.5 on 2025-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0017_tournament_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="prize_pool",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total prize pool in Rial.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
