# Generated by Django 5.2.5 on 2025-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0018_tournament_prize_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("coming_soon", "Coming Soon"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
