# Generated by Django 5.2.5 on 2025-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0019_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winner_slots",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Maximum number of winners eligible for rewards. Set to 1 for champion-only payouts.",
            ),
        ),
    ]
