# Generated by Django 5.2.5 on 2025-10-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0020_tournament_winner_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_token_based",
            field=models.BooleanField(default=False),
        ),
    ]
