# Generated by Django 5.2.5 on 2025-11-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("tournaments", "0021_tournament_is_token_based"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="participant1_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_participant1",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="participant2_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_participant2",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_matches",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="tournaments", to="teams.team"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="top_teams",
            field=models.ManyToManyField(
                blank=True, related_name="top_placements", to="teams.team"
            ),
        ),
    ]
