# Generated by Django 5.2.4 on 2025-07-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("support", "0002_supportassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="support_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="support.ticket",
            ),
        ),
    ]
