# Generated by Django 5.2.5 on 2025-11-21 20:20

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=common.fields.WebPImageField(upload_to="attachments/"),
        ),
    ]
