# Generated by Django 5.2.5 on 2025-11-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.ImageField(upload_to="attachments/"),
        ),
    ]
