# Generated by Django 5.2.5 on 2025-11-28 15:17

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketattachment",
            name="file",
            field=common.fields.OptimizedFileField(upload_to="support_attachments/"),
        ),
    ]
