# Generated by Django 5.2.5 on 2025-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_supportassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("closed", "بسته"),
                    ("answered", "پاسخ داده شده"),
                    ("pending", "در انتظار پاسخ"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
