# Generated by Django 5.2.8 on 2025-12-01 14:59

import common.fields
import common.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_alter_ticketattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketattachment",
            name="file",
            field=common.fields.OptimizedFileField(
                upload_to=common.utils.files.get_sanitized_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
