# Generated by Django 5.2.8 on 2025-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_alter_ticketattachment_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("closed", "بسته"),
                    ("answered", "پاسخ داده شده"),
                    ("pending", "در انتظار پاسخ"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
