# Generated by Django 5.2.5 on 2025-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_alter_ticketattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketattachment",
            name="file",
            field=models.FileField(upload_to="support_attachments/"),
        ),
    ]
