# Generated by Django 5.2.5 on 2025-11-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorprofile",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
