# Generated by Django 5.2.5 on 2025-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                unique_for_date="created_at",
                verbose_name="Slug",
            ),
        ),
    ]
