# Generated by Django 5.2.5 on 2025-02-16 00:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="attachments/")),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True)),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(config_name="default"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(config_name="default"),
        ),
        migrations.AlterField(
            model_name="revision",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(config_name="default"),
        ),
    ]
