# Generated by Django 5.2.5 on 2025-11-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_authorprofile_social_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorprofile",
            name="social_links",
        ),
    ]
