# Generated by Django 5.2.5 on 2025-11-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_customattachment_alter_comment_content_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomAttachment",
        ),
    ]
