# Generated by Django 5.2.5 on 2025-09-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/featured_images/",
                verbose_name="Featured Image",
            ),
        ),
    ]
