# Generated by Django 5.2.8 on 2025-12-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_options_post_is_hot_alter_category_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_at", "-id"]},
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes_count",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
