# Generated by Django 5.2.5 on 2025-11-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
