# Generated by Django 5.2.8 on 2025-12-27 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_options_post_is_hot_alter_category_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_at", "-id"]},
        ),
        migrations.AddField(
            model_name="media",
            name="crop_box",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="media",
            name="focus_point_x",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="media",
            name="focus_point_y",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="media",
            name="variants",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="post",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="revision",
            name="content",
            field=models.JSONField(),
        ),
    ]
