# Generated by Django 5.2.5 on 2025-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_comments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
