# Generated by Django 5.2.8 on 2025-12-27 10:59

from django.db import migrations

def convert_html_to_json(apps, schema_editor):
    """
    Converts the old HTML content of Post and Revision models to a basic
    JSON block structure.
    """
    Post = apps.get_model('blog', 'Post')
    Revision = apps.get_model('blog', 'Revision')

    for post in Post.objects.all():
        if isinstance(post.content, str) and post.content.strip():
            post.content = [{"type": "html_block", "data": {"html": post.content}}]
            post.save(update_fields=['content'])

    for revision in Revision.objects.all():
        if isinstance(revision.content, str) and revision.content.strip():
            revision.content = [{"type": "html_block", "data": {"html": revision.content}}]
            revision.save(update_fields=['content'])


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_options_media_crop_box_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_html_to_json, migrations.RunPython.noop),
    ]
