# Generated by Django 5.2.5 on 2025-11-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_comments_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments_count",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
