# Generated by Django 5.2.5 on 2025-11-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_post_comments_count_comment_is_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes_count",
        ),
    ]
