# Generated by Django 5.2.5 on 2025-11-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_post_is_published_remove_post_likes_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_approved",
        ),
    ]
