# Generated by Django 5.2.5 on 2025-11-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_comment_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="reading_time_sec",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
