# Generated by Django 5.2.5 on 2025-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_post_likes_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
