# Generated by Django 5.2.5 on 2025-11-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_media_size_bytes"),
    ]

    operations = [
        # Backfill NULLs before altering columns to be NOT NULL
        migrations.RunSQL(
            sql='''
                UPDATE "blog_post" SET "likes_count" = 0 WHERE "likes_count" IS NULL;
                UPDATE "blog_post" SET "views_count" = 0 WHERE "views_count" IS NULL;
            ''',
            reverse_sql=migrations.RunSQL.noop, # Optional: can't really reverse this
        ),
        migrations.AlterField(
            model_name="post",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="reading_time_sec",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
