# Generated by Django 5.2.5 on 2025-11-17 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="prizes/")),
                ("chance", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Wheel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "required_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tournaments.rank"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "prize",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rewards.prize"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "wheel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rewards.wheel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prize",
            name="wheel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prizes",
                to="rewards.wheel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spin",
            unique_together={("user", "wheel")},
        ),
    ]
