# Generated by Django 5.2.5 on 2025-11-28 15:17

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prize",
            name="image",
            field=common.fields.OptimizedImageField(upload_to="prizes/"),
        ),
    ]
