# Generated by Django 5.2.5 on 2025-10-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_transaction_description_alter_transaction_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="token_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("entry_fee", "Entry Fee"),
                    ("prize", "Prize"),
                    ("token_spent", "Token Spent"),
                    ("token_earned", "Token Earned"),
                ],
                max_length=20,
            ),
        ),
    ]
