# Generated by Django 5.2.8 on 2025-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_transaction_is_refunded_refund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("approved", "تایید شده"),
                    ("rejected", "رد شده"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
