# Generated by Django 5.2.8 on 2025-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_withdrawalrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="token_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="total_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="withdrawable_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
