# Generated by Django 5.2.5 on 2025-10-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_wallet_token_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="authority",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
