# Generated by Django 5.2.5 on 2025-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_transaction_authority_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="order_id",
            field=models.CharField(
                blank=True,
                help_text="Unique order ID for the transaction",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ref_number",
            field=models.CharField(
                blank=True,
                help_text="Zibal reference number after successful payment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="authority",
            field=models.CharField(
                blank=True,
                help_text="Zibal trackId",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
