# Generated by Django 5.2.5 on 2025-11-17 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="AtomGameBot", max_length=100, unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Activate the bot to start its tasks. Deactivate to stop.",
                    ),
                ),
            ],
            options={
                "verbose_name": "AtomGameBot Settings",
                "verbose_name_plural": "AtomGameBot Settings",
            },
        ),
        migrations.AddField(
            model_name="botsettings",
            name="author",
            field=models.OneToOneField(
                blank=True,
                help_text="The user account that will be the author of posts created by the bot.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
