# Generated by Django 5.0.6

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_bot_user_and_settings(apps, schema_editor):
    """
    Creates the 'AtomGameBot' user and the corresponding BotSettings instance.
    """
    User = apps.get_model('users', 'User')
    BotSettings = apps.get_model('atomgamebot', 'BotSettings')

    # Define bot user details
    bot_username = "AtomGameBot"
    bot_password = "a_secure_default_password_for_bot"  # This will be hashed.
    bot_phone_number = "+989000000001"  # A dummy, unique phone number to avoid collision with tests.

    # Using get_or_create to make the migration re-runnable without errors.
    bot_user, created = User.objects.get_or_create(
        username=bot_username,
        defaults={
            'password': make_password(bot_password),
            'phone_number': bot_phone_number,
            'is_staff': False,
            'is_superuser': False,
        }
    )

    if created:
        print(f"\\nCreated User: {bot_username}")

    # Create the BotSettings instance and link it to the user.
    BotSettings.objects.get_or_create(
        name="AtomGameBot",
        defaults={'author': bot_user}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('atomgamebot', '0001_initial'),
        ('users', '0001_initial'),  # Dependency on the users app
    ]

    operations = [
        migrations.RunPython(create_bot_user_and_settings),
    ]
