# Generated by Django 5.2.5 on 2025-11-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("report_new", "New Report"),
                            ("report_status_change", "Report Status Change"),
                            (
                                "winner_submission_required",
                                "Winner Submission Required",
                            ),
                            (
                                "winner_submission_status_change",
                                "Winner Submission Status Change",
                            ),
                        ],
                        default="report_status_change",
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
