# Generated by Django 5.2.4 on 2025-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("report_new", "New Report"),
                    ("report_status_change", "Report Status Change"),
                    ("winner_submission_required", "Winner Submission Required"),
                    (
                        "winner_submission_status_change",
                        "Winner Submission Status Change",
                    ),
                ],
                default="report_status_change",
                max_length=50,
            ),
        ),
    ]
