# Generated by Django 5.2.8 on 2025-12-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("report_new", "گزارش جدید"),
                    ("report_status_change", "تغییر وضعیت گزارش"),
                    ("winner_submission_required", "نیاز به ارسال نتیجه"),
                    ("winner_submission_status_change", "تغییر وضعیت ارسال نتیجه"),
                    ("verification_status_change", "تغییر وضعیت احراز هویت"),
                ],
                default="report_status_change",
                max_length=50,
            ),
        ),
    ]
